In [55]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import FactorAnalysis as FA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA

In [56]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length' , 'sepal-width' , 'petal-length' , 'petal-width' , 'Class']
dataset = pd.read_csv(url,names=names)

In [57]:
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

In [58]:
X_train , X_test , y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [59]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [60]:
classifier = RandomForestClassifier(max_depth=2,random_state=0)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

In [61]:
cm = confusion_matrix(y_test,y_pred)
print(cm)
print('Accuracy'+str(accuracy_score(y_test,y_pred)))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Accuracy0.9777777777777777


In [62]:
fa =FA(n_components=1)
X_train = fa.fit_transform(X_train)
X_test = fa.transform(X_test)

In [63]:
classifier = RandomForestClassifier(max_depth=2,random_state=0)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

In [64]:
cm = confusion_matrix(y_test,y_pred)
print(cm)
print('Accuracy'+str(accuracy_score(y_test,y_pred)))

[[16  0  0]
 [ 0 17  1]
 [ 0  1 10]]
Accuracy0.9555555555555556


In [65]:
def perform_pca(n):
    X_train , X_test ,y_train ,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
    pca = PCA(n_components = n)
    pca_x_train = pca.fit_transform(X_train)
    pca_x_test = pca.transform(X_test)
    classifier = RandomForestClassifier(max_depth = 2,random_state=0)
    classifier.fit(pca_x_train,y_train)
    y_pred = classifier.predict(pca_x_test)
    cm = confusion_matrix(y_test,y_pred)
    print(cm)
    print('Acuracy {0}\n\n'.format(accuracy_score(y_test,y_pred)))

In [66]:
for x in range(1,5):
    perform_pca(x)

[[16  0  0]
 [ 0 15  3]
 [ 0  1 10]]
Acuracy 0.9111111111111111


[[16  0  0]
 [ 0 15  3]
 [ 0  1 10]]
Acuracy 0.9111111111111111


[[16  0  0]
 [ 0  9  9]
 [ 0  1 10]]
Acuracy 0.7777777777777778


[[16  0  0]
 [ 0 15  3]
 [ 0  1 10]]
Acuracy 0.9111111111111111


