In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length' , 'sepal-width' , 'petal-length' , 'petal-width' , 'Class']
dataset = pd.read_csv(url,names=names)

In [4]:
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

In [5]:
X_train , X_test , y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [6]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
classifier = RandomForestClassifier(max_depth=2,random_state=0)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

In [8]:
cm = confusion_matrix(y_test,y_pred)
print(cm)
print('Accuracy'+str(accuracy_score(y_test,y_pred)))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Accuracy0.9777777777777777


In [10]:
lda =LDA(n_components=1)
X_train = lda.fit_transform(X_train,y_train)
X_test = lda.transform(X_test)

In [11]:
classifier = RandomForestClassifier(max_depth=2,random_state=0)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

In [12]:
cm = confusion_matrix(y_test,y_pred)
print(cm)
print('Accuracy'+str(accuracy_score(y_test,y_pred)))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Accuracy0.9777777777777777
