In [46]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [47]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length' , 'sepal-width' , 'petal-length' , 'petal-width' , 'Class']
dataset = pd.read_csv(url,names=names)

In [48]:
dataset

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [49]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [50]:
X = dataset.drop('Class',1)
y = dataset['Class']

C:\Users\KISHOR WAGH\AppData\Local\Temp\ipykernel_25384\2271304027.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = dataset.drop('Class',1)


In [51]:
X.shape,y.shape

((150, 4), (150,))

In [52]:
X_train , X_test , y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [53]:
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [54]:
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.92565521, 0.05388883, 0.01624092, 0.00421505])

In [55]:
def perform_pca(n):
    X_train , X_test ,y_train ,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
    pca = PCA(n_components = n)
    pca_x_train = pca.fit_transform(X_train)
    pca_x_test = pca.transform(X_test)
    classifier = RandomForestClassifier(max_depth = 2,random_state=0)
    classifier.fit(pca_x_train,y_train)
    y_pred = classifier.predict(pca_x_test)
    cm = confusion_matrix(y_test,y_pred)
    print(cm)
    print('Acuracy {0}\n\n'.format(accuracy_score(y_test,y_pred)))

In [56]:
for x in range(1,5):
    perform_pca(x)

[[16  0  0]
 [ 0 15  3]
 [ 0  1 10]]
Acuracy 0.9111111111111111


[[16  0  0]
 [ 0 15  3]
 [ 0  1 10]]
Acuracy 0.9111111111111111


[[16  0  0]
 [ 0  9  9]
 [ 0  1 10]]
Acuracy 0.7777777777777778


[[16  0  0]
 [ 0 15  3]
 [ 0  1 10]]
Acuracy 0.9111111111111111


